name: Manual CI - Test & Build

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
  REPOSITORY_OWNER:
    description: "Owner of the repository"
    required: true
  UNIT_TEST_COMMAND:
    description: "Command to run unit tests"
    required: true
  API_NAME:
    description: "Name of the API"
    required: true

runs: 

  using: "composite"

  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      shell: bash
      run: ${{ inputs.UNIT_TESTS_COMMAND }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure()
      with:
        report_paths: ${{ inputs.REPORT_PATH }}

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      continue-on-error: true
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: "60 80"

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.REPOSITORY_OWNER }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/llnabsll/${{ inputs.API_NAME }}/${{ inputs.API_NAME }}:1.0
